### PR TITLE
Support checking out submodules, and do so by default

### LINKED ISSUE #38: Git submodules support
It looks like git submodules aren't getting checked out after setting up a repo according to the instructions: https://dev.azure.com/benesaunders/benesaunders/_build/results?buildId=2

I need this for https://github.com/Ralith/openxrs. [It seems to be possible](https://docs.microsoft.com/en-us/azure/devops/pipelines/repos/pipeline-options-for-git?view=azure-devops), but it's not clear to me how to apply that here.

### PR DESCRIPTION
**Pull request by Ralith**
Untested, but probably fixes #38.

### CODE REVIEW

**Comment by jonhoo** [comment]
We should probably list this in the `parameters` list at the top of each file.

Though I wonder (cc @epage) whether we'll soon want basically a build pipeline for our CI scripts. We're starting to repeat the same things in many places..

**Comment by Ralith** [comment]
> We should probably list this in the parameters list at the top of each file.

Updated. Although it seems like this isn't always done currently, e.g. `parameters.codecov_token` in coverage.yml.

**Comment by jonhoo** [comment]
I'm still debating whether we actually want to make submodule checkout a part of the CI scripts themselves (see https://github.com/crate-ci/azure-pipelines/issues/38#issuecomment-513571925). It _seems_ better for me to set this as a property of the pipeline, something Azure Pipelines already supports. Though in that case we'd definitely need to document it better.

**Comment by Ralith** [comment]
I'm not sure what that means, and moving things to a web UI instead of a declarative config file seems dicey, but so long as I can build openxrs I'll be happy.

**Comment by jonhoo** [comment]
So, in the Pipelines web UI, if you click your pipeline, then Edit (top right), the three-dots button (top right), then Triggers, then select the tab "YAML", then "Get sources" in the list, you'll get the same menu you get as when you first added the pipeline. In that menu, there's a checkbox towards the bottom that says "Checkout submodules". Checking that and clicking the "Save" button near the top should do it.

Of course, that's a _terrible_ process to have to go through, but I think the idea (from Microsoft's side, not sure I agree with it) is that the developer will check off that checkbox when they first set up the pipeline. It is also terribly documented (bottom of [checkout](https://docs.microsoft.com/en-us/azure/devops/pipelines/repos/github?view=azure-devops&tabs=yaml#submodules), if that can even be called documentation).

After having written all that, I think I agree with you that it should just be in the scripts and on by default :p

**Pull request merged**
